VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Class1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Sub Msg(name As String)
    MsgBox name & "Ç≥ÇÒ Ç±ÇÒÇ…ÇøÇÕÅB"
End Sub

Function Total(n1 As Double, n2 As Double, n3 As Double) As Double
    Total = n1 + n2 + n3
End Function
